name: Github JD-sign bot

on:
    push:
        branches:
            - master
    # workflow_dispatch: # 手动触发
    schedule:
        - cron: '5 16 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                  ref: 'dev'
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node app.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                JD_COOKIE_2: ${{ secrets.JD_COOKIE_2 }} 
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
                WX_PUSHER : ${{ secrets.WX_PUSHER }}
                WX_PUSHER_UID  : ${{ secrets.WX_PUSHER_UID }}
